---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-sena-deploy
  labels:
    app: ms-sena
spec:
  selector:
    matchLabels:
      app: ms-sena
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ms-sena
    spec:
      containers:
        - name: ms-sena
          image: acjimeneza/ms-sena:1
          env:
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                key: username
                name: secret-base-auth
          - name: USER_NAME_OPEN
            valueFrom:
              secretKeyRef:
                key: usernameopen
                name: secret-base-opaque
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-sena
  labels:
    app: ms-sena
spec:
  type: LoadBalancer
  selector:
    app: ms-sena
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000


