---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-sena-deploy
  labels:
    app: front-sena
spec:
  selector:
    matchLabels:
      app: front-sena
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: front-sena
    spec:
      containers:
        - name: front-sena
          image: acjimeneza/front-sena:1
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---

---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front-sena
spec:
  type: LoadBalancer
  selector:
    app: front-sena
  ports:
    - protocol: TCP
      name: http
      port: 4200
      targetPort: 4200

